### ISSUE TITLE
CSS styles not loading

### ISSUE THREAD

**Issue by lauragift21** [waseembarcha/vuejs-crud#1]
The styling of the application is not loading. Could be possible the stylesheet is not being linked correctly.

**Comment by ghost** [comment]
@lauragift21 did you built the application using `npm run build` command?

**Comment by waseembarcha** [comment]
@lauragift21 If you build the app for production then you can make the local assets paths relative in index.html, by default they are absolute.
More details here: 
[(https://github.com/vuejs-templates/webpack/issues/1266)]((https://github.com/vuejs-templates/webpack/issues/1266))

**Comment by lauragift21** [comment]
@iksdatoo Yeah, I did. But it still looks the same way as the link provided on the repo that why i figured something was missing.

**Comment by Mart-Bogdan** [comment]
The problem was with bootstrap CDN.
I would fine a PR soon with this issue fixed, by installing bootstrap into node_modules
